apiVersion: v1
kind: Secret
metadata:
  name: rails-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SECRET_KEY_BASE: {{ required "backend.secret.SECRET_KEY_BASE is required" .Values.backend.secret.SECRET_KEY_BASE | quote }}