apiVersion: v1
kind: Secret
metadata:
  name: rails-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: neighborly-library
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: backend
type: Opaque
stringData:
  SECRET_KEY_BASE: {{ required "backend.secret.SECRET_KEY_BASE is required" .Values.backend.secret.SECRET_KEY_BASE | quote }}
