apiVersion: v1
kind: Service
metadata:
  name: {{ include "nl.frontendName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "nl.frontendName" . }}
    app.kubernetes.io/name: neighborly-library
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app: {{ include "nl.frontendName" . }}
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.frontend.port }}
