{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-nginx-to-frontend
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "nl.frontendName" . }}
  policyTypes:
    - Ingress
  ingress:
    # Ingress Controller -> Frontend
    - from:
        - namespaceSelector:
            matchLabels:
              {{ .Values.networkPolicy.ingressNamespaceLabelKey }}: {{ .Values.networkPolicy.ingressNamespaceLabelValue }}
      ports:
        - protocol: TCP
          port: {{ .Values.frontend.port }}
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: helm-test
      ports:
        - protocol: TCP
          port: {{ .Values.frontend.port }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-to-backend
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "nl.backendName" . }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        # Frontend -> Backend
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: frontend
        # Helm tests -> Backend
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: helm-test
      ports:
        - protocol: TCP
          port: {{ .Values.backend.port }}
{{- end }}
